language: java
before_install:
  - sudo ant download-ivy -Dskip.download=flase
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: sudo ant test -Dskip.download=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

